apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage-1 
  description: Test Repo for backstage registration
  annotations:
    github.com/project-slug: lytt925/test-backstage-1
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:my-group
  lifecycle: production
  system: my-system
  providesApis:
    - test-backstage-1-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-backstage-1-api 
  description: All APIs of test-backstage-1
  links:
    - url: https://github.com/lytt925/test-backstage-1/tree/main
      title: GitHub Repo
      icon: github
spec:
  type: raw-openapi
  lifecycle: production
  owner: group:my-group
  system: my-system
  definition:
    $text: ./docs/openapi.yaml
