openapi: "3.0.0"
info:
  title: Hello World API
  version: "1.0.0"
paths:
  /hello:
    get:
      summary: Returns a friendly greeting
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: "Hello, world!"

